# Site Build Settings

# jekyll-paginate configuration
paginate:            5

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           /:title
plugins:             [jekyll-paginate, jekyll-sitemap, jekyll-feed, jekyll-seo-tag]
theme:               jekyll-theme-minimal

# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)
title:		           "Tomorrow's Blog"
email:               "zjmzjm606@gmail.com   zjmzjm66@connect.hku.hk"
url:                 "https://zjmzjm606.github.io"

social_links:
  twitter: "https://twitter.com/your_username"
  github: "https://github.com/your_username"
  linkedin: "https://www.linkedin.com/in/your_profile"

# RSS 2.0 can be used instead of Atom by uncommenting following two lines
#feed:
#  path: rss-feed.xml
